import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { assembleReportSource, renderReport } from '@vibefy/report';
import { resolvePlan } from '@vibefy/billing';
import { createClient } from '@/lib/supabase/server';
import { readAsUser } from '@/lib/sql';

export const metadata: Metadata = { title: 'Report' };

/**
 * The report, on screen.
 *
 * Rendered from the same assembly the PDF uses, under the caller's own
 * row-level-security identity — so a customer sees their own report and nobody
 * else's, by construction rather than by a WHERE clause we remembered to write.
 *
 * The tier decides what is shown. It never decides what was scored.
 */
export default async function ReportPage({
  params,
}: {
  params: Promise<{ assessmentId: string }>;
}) {
  const { assessmentId } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect(`/sign-in?next=/console/reports/${assessmentId}`);

  const page = await readAsUser(user.id, async (client) => {
    const context = await client.query<{ organisation_id: string; app_id: string; status: string }>(
      'select organisation_id, app_id, status from public.assessments where id = $1',
      [assessmentId],
    );
    const row = context.rows[0];
    if (!row) return null;

    const plan = await resolvePlan(client, {
      organisationId: row.organisation_id,
      appId: row.app_id,
    });
    const source = await assembleReportSource(client, assessmentId);
    return { source, plan, status: row.status };
  });

  if (!page) notFound();

  if (page.status !== 'approved' && page.status !== 'published') {
    return (
      <div className="max-w-2xl space-y-4">
        <h1 className="text-3xl font-bold tracking-tight">Report not ready</h1>
        <p className="text-muted">
          This assessment is {page.status.replace(/_/g, ' ')}. Nothing is published until a human
          reviewer has approved it — AI never certifies alone, and that includes publishing.
        </p>
        <Link href="/console">Back to the console</Link>
      </div>
    );
  }

  const rendered = renderReport(page.source, page.plan.entitlement.reportTier);

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <p className="text-sm text-muted">{page.plan.because}</p>
          <h1 className="text-2xl font-bold tracking-tight">Assessment report</h1>
        </div>
        {page.plan.entitlement.pdfExport ? (
          <a
            href={`/console/reports/${assessmentId}/pdf`}
            className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-white"
          >
            Download PDF
          </a>
        ) : (
          <Link
            href={`/console/billing?app=${page.source.assessmentId}`}
            className="rounded-lg border border-line-strong px-4 py-2 text-sm font-medium"
          >
            Get the full report
          </Link>
        )}
      </div>

      {rendered.withheld.length > 0 && (
        <section
          aria-labelledby="withheld"
          className="rounded-xl border border-line bg-surface-muted p-5"
        >
          <h2 id="withheld" className="font-semibold">
            You are reading the free report
          </h2>
          <p className="mt-2 text-sm text-muted">The full report adds:</p>
          <ul className="mt-2 space-y-1 text-sm text-muted">
            {rendered.withheld.map((item) => (
              <li key={item}>· {item}</li>
            ))}
          </ul>
          <p className="mt-3 text-sm">
            Your score is the same either way. Payment buys depth, evidence and support — never a
            different number.
          </p>
        </section>
      )}

      {/* The report document is generated by us from our own data and is escaped
          at render time; it is not customer-supplied markup. */}
      <iframe
        title={rendered.title}
        srcDoc={rendered.html}
        className="h-[80vh] w-full rounded-xl border border-line bg-surface"
      />
    </div>
  );
}
