#!/usr/bin/env tsx
/**
 * Carries the supplied badge artwork into the badge package.
 *
 * The badge served to a customer's website used to be drawn: a traced mark, a
 * generated wordmark, an arc of text and a struck band, assembled in code. It
 * was a good reconstruction and it was not the trade mark. The founder put it
 * plainly — a product cannot ship with a drawn badge — and he is right, because
 * the one thing this mark has to be is the same mark everywhere.
 *
 * So the four states are read from the generated masters, resized once, and
 * written out as data URIs the renderer embeds. Two consequences worth stating:
 *
 *   · 256 pixels, not 640. This image loads on other people's websites, at a
 *     displayed size of 96 to 128 — so 256 is sharp on a retina screen and
 *     costs about a tenth of the full master. The bytes a visitor pays for are
 *     not ours to be generous with.
 *   · The checksum of each source master is recorded beside it. `check:brand`
 *     used to prove the badge's colours came from the palette; a raster has no
 *     colours to read, so the guarantee changes shape — from "these are our
 *     colours" to "this is the supplied artwork, unaltered".
 *
 * Run after `pnpm brand:build`, which is what produces the masters this reads.
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const brandDir = join(root, 'apps/web/public/brand');
const target = join(root, 'packages/badge/src/artwork.generated.ts');

/** Twice the size the badge is displayed at, which the licence floors at 96px. */
const BADGE_PX = 256;

const STATES = [
  { status: 'active', file: 'vibefycode-badge-artwork.webp' },
  { status: 'suspended', file: 'vibefycode-badge-artwork-suspended.webp' },
  { status: 'expired', file: 'vibefycode-badge-artwork-expired.webp' },
  { status: 'revoked', file: 'vibefycode-badge-artwork-revoked.webp' },
] as const;

const missing = STATES.filter((state) => !existsSync(join(brandDir, state.file)));
if (missing.length > 0) {
  console.error(
    `Missing badge artwork: ${missing.map((state) => state.file).join(', ')}.\n` +
      'Run `pnpm brand:build` first — this tool resizes what that produces rather than redrawing it.',
  );
  process.exit(1);
}

const entries: string[] = [];
for (const state of STATES) {
  const source = readFileSync(join(brandDir, state.file));
  const resized = await sharp(source)
    .resize(BADGE_PX, BADGE_PX, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    // Lossless alpha, so the seal's edge does not fringe against whatever ground
    // a customer's page happens to have.
    .webp({ quality: 88, alphaQuality: 100 })
    .toBuffer();

  entries.push(
    `  ${state.status}: {\n` +
      `    /** sha256 of \`${state.file}\`, the master this was resized from. */\n` +
      `    sourceSha256: '${createHash('sha256').update(source).digest('hex')}',\n` +
      `    bytes: ${resized.byteLength},\n` +
      `    dataUri:\n      'data:image/webp;base64,${resized.toString('base64')}',\n` +
      `  },`,
  );
  console.log(
    `  ${state.status.padEnd(10)} ${String(source.byteLength).padStart(7)} B → ${String(resized.byteLength).padStart(6)} B`,
  );
}

const file = `/**
 * The supplied badge artwork, one entry per state.
 *
 * Generated by \`pnpm badge:artwork\` from the masters in
 * \`apps/web/public/brand\`. Do not edit: the point of this file is that the mark
 * on a customer's website is the supplied one, byte for byte, rather than a
 * drawing of it that drifts.
 *
 * Resized to ${BADGE_PX}px because the badge is displayed at 96 to 128 and this
 * image loads on other people's pages.
 */

export interface BadgeArtwork {
  readonly sourceSha256: string;
  readonly bytes: number;
  readonly dataUri: string;
}

export const BADGE_ARTWORK_PX = ${BADGE_PX};

export const BADGE_ARTWORK: Readonly<Record<'active' | 'suspended' | 'expired' | 'revoked', BadgeArtwork>> = {
${entries.join('\n')}
};
`;

writeFileSync(target, file);
console.log(`✓ Wrote ${target} (${(file.length / 1024).toFixed(0)} KB)`);
