#!/usr/bin/env node
/**
 * Copy lint — the language-discipline gate.
 *
 * "Verified by VibefyCode" is defensible only because it is narrow. The moment any surface
 * says the word this file forbids, the mark stops meaning "assessed against a published
 * rubric on a date" and starts meaning "safe", which is a claim we cannot support and did
 * not sell. This gate exists so that drift is caught by CI rather than by a regulator or a
 * customer's lawyer.
 *
 * Two rule classes:
 *   1. FORBIDDEN — phrases that are never permissible anywhere. No escape hatch.
 *   2. RESTRICTED — absolute words permitted only inside a sentence that negates or scopes
 *      them ("this is not a guarantee that the application is secure"). An unavoidable
 *      exception can be marked on the preceding line with:
 *          vibefycode-copy-lint-allow: <reason>
 *      The reason is mandatory; a bare suppression is itself a failure.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative, extname } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Surfaces whose words reach a customer, a regulator or a court. */
const SCAN_DIRS = ['apps', 'packages', 'legal', 'brand', 'supabase'];
const SCAN_FILES = ['README.md'];
const SCAN_EXTENSIONS = new Set([
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.md',
  '.mdx',
  '.sql',
  '.html',
  '.txt',
]);
const SKIP_DIRS = new Set([
  'node_modules',
  '.next',
  'dist',
  'build',
  'coverage',
  '.git',
  // `png` and `icons` hold nothing but binaries. `source` used to be listed here
  // for the same reason and is not any more: it now holds prose about the marks,
  // and prose about the marks is exactly what this gate exists to read.
  'png',
  'icons',
]);
/**
 * Files this gate cannot usefully read.
 *
 * The first two necessarily contain every forbidden phrase, and the tests
 * assert on them.
 *
 * The third is a generated migration whose body is a verbatim copy of
 * `packages/rubric/versions/1.0.0.json` — data, not prose, and never scanned
 * here because `.json` is not a scanned extension. It trips the gate on a
 * rubric check that names the `Secure` cookie attribute, which is the flag's
 * name rather than a claim about anything. Skipping it is safe only because
 * `tests/rubric-published.test.ts` pins the payload to the rubric the scoring
 * code loads: prose smuggled into this file would fail that test instead.
 *
 * The fourth is generated by concatenating every migration, so scanning it
 * lints the same bytes a second time and reports one edit as two violations.
 * Each migration is still read on its own, and `tests/deployment.test.ts`
 * asserts the concatenation is exactly what they produce, so nothing reaches
 * the database through this file without passing the gate on the way in.
 */
const SKIP_FILES = new Set([
  'tools/copy-lint.mjs',
  'tools/copy-lint.test.ts',
  'supabase/migrations/20260830110000_publish_rubric_1_0_0.sql',
  'supabase/schema.sql',
  // A fifth, for the same reason as the first two: it is the list of phrases
  // the assistant may not send, so it necessarily contains every one of them.
  // Kept to the list alone — `packages/copilot/src/index.ts` holds the prose
  // the assistant is instructed with and stays scanned, which
  // `tests/copilot-route.test.ts` asserts.
  'packages/copilot/src/guard.ts',
  // And its tests, for the reason `tools/copy-lint.test.ts` is here: a test
  // that proves a phrase is refused has to contain the phrase.
  'packages/copilot/src/copilot.test.ts',
]);

/** Never permitted. These extend the mark into a claim we do not make. */
export const FORBIDDEN_PHRASES = [
  'vibefycode verified secure',
  'vibefycode certified safe',
  'vibefycode approved',
  'guaranteed by vibefycode',
  'vibefycode compliant',
  'vibefycode certified secure',
  'certified secure',
  'hack-proof',
  'hackproof',
  'unhackable',
  'bank-grade security',
  'military-grade security',
  '100% secure',
  'fully secure',
  'guaranteed secure',
  'penetration tested by vibefycode',
];

/**
 * The wordmark is exactly "Verified by VibefyCode". Anything of the shape
 * "VibefyCode <strong-adjective>" or "<strong-adjective> by VibefyCode" is an extension of the mark.
 */
export const MARK_EXTENSION_PATTERN =
  /\bvibefycode[\s-]+(verified|certified|approved|secure|safe|compliant|guaranteed|trusted)\b|\b(certified|approved|guaranteed|secured)\s+by\s+vibefycode\b/i;

/**
 * The old name, on its own.
 *
 * The brand is VibefyCode. "Vibefy" was the name until the rename, and a
 * half-renamed sentence is the most likely way for the wrong one to reach a
 * customer — it reads fine to whoever wrote it. Anything that genuinely needs
 * the old name (the superseded artwork, this comment) says so with a reason.
 */
export const STALE_BRAND_PATTERN = /\bvibefy(?!code)\b/i;

/** Absolute words that require a negation or a scope qualifier in the same sentence. */
export const RESTRICTED_WORDS = [
  'secure',
  'safe',
  'guaranteed',
  'guarantee',
  'compliant',
  'risk-free',
  'bug-free',
  'error-free',
];

/** Markers that make a restricted word acceptable, because the sentence limits it. */
const QUALIFIERS = [
  'not',
  'never',
  'no ',
  'nor ',
  'cannot',
  "isn't",
  "doesn't",
  'does not',
  'without',
  'rather than',
  'instead of',
  'forbidden',
  'prohibited',
  'must not',
  'may not',
  'do not',
  'stops short of',
  'absence of',
];

function collectFiles(dir, out = []) {
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const entry of entries) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    const stats = statSync(full);
    if (stats.isDirectory()) collectFiles(full, out);
    else if (SCAN_EXTENSIONS.has(extname(entry))) out.push(full);
  }
  return out;
}

/** Split on sentence boundaries so a negation three sentences away cannot launder a claim. */
function sentencesOf(line) {
  return line.split(/(?<=[.!?;:])\s+|\s+[—–|]\s+/);
}

export function lintText(text, path = '<input>') {
  const violations = [];
  const lines = text.split('\n');
  const { suppressed, blockViolations } = suppressedBlocks(lines, path);
  violations.push(...blockViolations);

  // Phrase-level rules are line-local: a forbidden phrase is forbidden wherever it appears.
  lines.forEach((line, index) => {
    if (suppressed.has(index)) return;
    const lower = line.toLowerCase();
    for (const phrase of FORBIDDEN_PHRASES) {
      if (lower.includes(phrase)) {
        violations.push({
          path,
          line: index + 1,
          rule: 'forbidden-phrase',
          detail: `"${phrase}" is never permitted. The mark is exactly "Verified by VibefyCode".`,
        });
      }
    }
    const markMatch = MARK_EXTENSION_PATTERN.exec(line);
    if (markMatch && !/verified by vibefycode/i.test(line)) {
      violations.push({
        path,
        line: index + 1,
        rule: 'mark-extension',
        detail: `"${markMatch[0]}" extends the certification mark. Permitted forms: "Verified by VibefyCode", "VibefyCode-assessed", "VibefyCode Rubric vX — score N/100".`,
      });
    }
    const staleMatch = STALE_BRAND_PATTERN.exec(line);
    if (staleMatch) {
      violations.push({
        path,
        line: index + 1,
        rule: 'stale-brand',
        detail: `"${staleMatch[0]}" is the old name. The brand is VibefyCode, and the mark is exactly "Verified by VibefyCode".`,
      });
    }
    const inline = /vibefycode-copy-lint-allow:([^\n]*)/.exec(lower);
    if (inline && !isMeaningfulReason(inline[1])) {
      violations.push({
        path,
        line: index + 1,
        rule: 'suppression-without-reason',
        detail: 'A copy-lint suppression must state why the wording is correct.',
      });
    }
  });

  // Restricted words are judged per paragraph, not per line: prose wraps, and a negation
  // that lands on the previous physical line still scopes the sentence it belongs to.
  for (const block of paragraphsOf(lines, suppressed)) {
    const inlineAllow = /vibefycode-copy-lint-allow:([^\n]*)/.exec(block.text);
    if (inlineAllow && isMeaningfulReason(inlineAllow[1])) continue;
    const lower = block.text.toLowerCase();
    for (const sentence of sentencesOf(lower)) {
      for (const word of RESTRICTED_WORDS) {
        const pattern = new RegExp(`\\b${word.replace(/[-\s]/g, '[-\\s]')}\\b`);
        if (!pattern.test(sentence)) continue;
        if (QUALIFIERS.some((q) => sentence.includes(q))) continue;
        violations.push({
          path,
          line: block.line,
          rule: 'unqualified-absolute',
          detail: `"${word}" used without a negation or scope qualifier in "${sentence.trim().slice(0, 90)}". Say what was assessed, not what is true.`,
        });
      }
    }
  }

  return violations;
}

/**
 * Marks the line numbers inside a reasoned block suppression, and reports blocks
 * that give no reason or are never closed.
 */
function suppressedBlocks(lines, path) {
  const suppressed = new Set();
  const blockViolations = [];
  let openedAt = null;

  lines.forEach((line, index) => {
    if (/vibefycode-copy-lint-allow-block-end/.test(line)) {
      if (openedAt !== null) suppressed.add(index);
      openedAt = null;
      return;
    }
    const opener = /vibefycode-copy-lint-allow-block:(.*)$/.exec(line);
    if (opener) {
      if (!isMeaningfulReason(opener[1])) {
        blockViolations.push({
          path,
          line: index + 1,
          rule: 'suppression-without-reason',
          detail: 'A copy-lint block suppression must state why the wording is correct.',
        });
      }
      openedAt = index;
      suppressed.add(index);
      return;
    }
    if (openedAt !== null) suppressed.add(index);
  });

  if (openedAt !== null) {
    blockViolations.push({
      path,
      line: openedAt + 1,
      rule: 'unclosed-suppression',
      detail:
        'A copy-lint block suppression was opened and never closed, silencing the rest of the file.',
    });
  }

  return { suppressed, blockViolations };
}

/**
 * A suppression must say why. Comment terminators are stripped first, so
 * `<!-- vibefycode-copy-lint-allow-block: -->` reads as the empty reason it is
 * rather than as the string "-->".
 */
function isMeaningfulReason(raw) {
  const reason = String(raw ?? '')
    .replace(/(-->|\*\/|#>)\s*$/, '')
    .trim();
  return reason.length >= 10;
}

/**
 * A module specifier is somebody else's package name, not our copy.
 *
 * `react-native-safe-area-context` is not a claim that anything is safe, and
 * suppressing it file by file would train contributors to reach for the
 * suppression comment — which is the one habit this gate cannot afford.
 */
const MODULE_SPECIFIER =
  /^\s*(?:import\b|export\s+(?:\*|\{)|const\s+.*=\s*require\(|from\s+['"]|@import\b)/;

/** Consecutive non-blank lines, joined, so wrapped prose is judged as the sentence it is. */
function paragraphsOf(lines, suppressed = new Set()) {
  const blocks = [];
  let current = null;
  lines.forEach((line, index) => {
    if (suppressed.has(index)) {
      current = null;
      return;
    }
    if (line.trim() === '') {
      current = null;
      return;
    }
    if (MODULE_SPECIFIER.test(line)) {
      current = null;
      return;
    }
    if (current === null) {
      current = { line: index + 1, text: line };
      blocks.push(current);
    } else {
      current.text += ' ' + line;
    }
  });
  return blocks;
}

export function runCopyLint() {
  const files = [
    ...SCAN_DIRS.flatMap((dir) => collectFiles(join(root, dir))),
    ...SCAN_FILES.map((file) => join(root, file)),
  ];
  const violations = [];
  for (const file of files) {
    const rel = relative(root, file);
    if (SKIP_FILES.has(rel)) continue;
    violations.push(...lintText(readFileSync(file, 'utf8'), rel));
  }
  return { violations, fileCount: files.length };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { violations, fileCount } = runCopyLint();
  if (violations.length > 0) {
    console.error(`\n✗ Copy lint failed — ${violations.length} violation(s):\n`);
    for (const v of violations)
      console.error(`  ${v.path}:${v.line}  [${v.rule}]\n      ${v.detail}`);
    console.error('\nIf the wording is genuinely unavoidable, add on the line above:');
    console.error('  vibefycode-copy-lint-allow: <why this wording is correct>\n');
    process.exit(1);
  }
  console.log(`✓ Copy lint passed — ${fileCount} files, no over-claiming language.`);
}
