#!/usr/bin/env node
/**
 * Generates the CSS custom properties the web console uses, from the same
 * tokens.json the contrast gate checks and the badge renders from. Hand-editing
 * the generated file is how a product ends up with three slightly different blues.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(root, 'packages/shared/design/tokens.json'), 'utf8'));

const kebab = (key) => key.replace(/[A-Z]/g, (character) => `-${character.toLowerCase()}`);

const declarations = (map, indent = '  ') =>
  Object.entries(map)
    .filter(([key]) => !key.startsWith('$'))
    .map(([key, value]) => `${indent}--vibefy-${kebab(key)}: ${value};`)
    .join('\n');

const css = `/* Generated by tools/tokens-build.mjs — do not edit. Change packages/shared/design/tokens.json. */

:root {
${declarations(tokens.brand)}
${declarations(tokens.semantic.light)}
  --vibefy-gradient-primary: ${tokens.gradient.primary};
  color-scheme: light dark;
}

@media (prefers-color-scheme: dark) {
  :root {
${declarations(tokens.semantic.dark, '    ')}
  }
}

:root[data-theme='dark'] {
${declarations(tokens.semantic.dark)}
}

:root[data-theme='light'] {
${declarations(tokens.semantic.light)}
}
`;

const target = join(root, 'apps/web/app/tokens.css');
writeFileSync(target, css);
console.log('✓ Design tokens written to apps/web/app/tokens.css');
