#!/usr/bin/env node
/**
 * Generates the CSS custom properties the web console uses, from the same
 * tokens.json the contrast gate checks and the badge renders from. Hand-editing
 * the generated file is how a product ends up with three slightly different blues.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(root, 'packages/shared/design/tokens.json'), 'utf8'));

const kebab = (key) => key.replace(/[A-Z]/g, (character) => `-${character.toLowerCase()}`);

const declarations = (map, indent = '  ') =>
  Object.entries(map)
    .filter(([key]) => !key.startsWith('$'))
    .map(([key, value]) => `${indent}--vibefycode-${kebab(key)}: ${value};`)
    .join('\n');

const css = `/* Generated by tools/tokens-build.mjs — do not edit. Change packages/shared/design/tokens.json. */

/*
 * Dark is the product, not a preference.
 *
 * This used to follow the operating system: light by default, dark only if the
 * viewer's machine asked for it. That makes the palette an accident of someone
 * else's settings, and it meant most people saw a blue-on-white page for a
 * product whose whole subject is what happens inside software.
 *
 * So the dark set is the bare \`:root\` — what everyone gets — and there is no
 * \`prefers-color-scheme\` rule. Light survives as an explicit opt-in, because
 * two things genuinely need it: a report that will be printed, and a customer
 * who has asked for it.
 */
:root {
${declarations(tokens.brand)}
${declarations(tokens.semantic.dark)}
  --vibefycode-gradient-primary: ${tokens.gradient.primary};
  color-scheme: dark;
}

:root[data-theme='light'] {
${declarations(tokens.semantic.light)}
  color-scheme: light;
}

:root[data-theme='dark'] {
${declarations(tokens.semantic.dark)}
  color-scheme: dark;
}
`;

const target = join(root, 'apps/web/app/tokens.css');
writeFileSync(target, css);
console.log('✓ Design tokens written to apps/web/app/tokens.css');
